name: jh_debug
description: jh_debug The debugging plug-in above the APP. Easy-to-use console plugin, More feature details....
version: 2.0.0
homepage: https://github.com/tec8297729/jh_debug

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
